---
- name: playbook_2
  hosts: nodes
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: uninstall_apache
    yum:
      name:
        httpd
      state: absent


  - name: delete file /var/www/html/index.html with content
    ansible.builtin.file:
      path: "/var/www/html/index.html"
      state: absent

  - name: open ports
    firewalld:
      port: 80/tcp
      immediate: yes
      permanent: yes
      state: disabled

  - name: open ports
    firewalld:
      port: 22/tcp
      immediate: yes
      permanent: yes
      state: disabled

  - name: open ports
    firewalld:
      port: 111/tcp
      immediate: yes
      permanent: yes
      state: disabled
